copy-image.yml, files/rhel-guest-image.txt, files/test.txt, roles/defaults/main.yml
Added a copy image playbook to test sending the kvm image files.  Had to test conditional logic.  Will update for correct destination.
=> added sample copy image file to test logic in playbook

README.md
Changes to README file based on Lesson 3 of our video journey.
=> updated readme file in lesson 3

inventory
Updated inventory file for your review
=> added ip addresses to inventory file

test01-psw.yml
Renamed test01.yml to test01-psw.yml
=> renamed test01.yml to avoid conflits

list_vms.yml
rename yaml file to more accurately describe what it does.
=> test yml file for displaying running vms

dwnload-image-files.yml
Tested this on my home ubuntu server.  Need to test on our KVM host.
=> Added playbook to download the RHCOS images

get-ocp.yml
I am putting this in the main directory.  Repurpose and remove
=> added download and copy of OCP client and installer playbook

.gitignore, files/rhel83.iso
adding iso to gitignore and fake rhel83.iso in files directory.
=> modify gitignore and contents of files directory

roles/check_dns/tasks/main.yaml
This code, will verify the dns configuration, not only test if the FQDNs resolves to IP. It will also verify that each FQDN for each node really matches the node's IP defined into the env.yaml
This is not 100% my contribution, Jacob heavily contributed to this code as well.
=> improvement to the check_dns

roles/attach_subscription/tasks/main.yaml
=> fix: Add retry if subscription server is not available

roles/create_bastion/templates/bastion-ks.cfg.j2
Add missing network device parameter and network hostname. Add yum repositories, to install packages from local ftp/http server Fix issue with wrong package name in package section
Signed-off-by: Klaus Smolin <SMOLIN@de.ibm.com>
=> fix(create-bastion): Update bastion-ks.cfg

roles/create_bootstrap/tasks/main.yaml, roles/create_compute_nodes/tasks/main.yaml, roles/create_control_nodes/tasks/main.yaml
=> fix: Enable autostart for control, compute and infra VMs

roles/wait_for_bootstrap/tasks/main.yaml
=> fix: Wrong long line break

roles/create_bastion/templates/bastion-ks.cfg.j2
Hostname was not correctly defined in ks
nameserver2 variable was not correctly used in ks
=> fix: Problem with hostname and 2nd nameserver definition

inventories/default/group_vars/all.yaml.template
Templates need to be synchronized with the latest changes
=> update template file

roles/create_compute_nodes/tasks/main.yaml, roles/create_control_nodes/tasks/main.yaml
=> fix: Create nodes on LPAR1 in non high availability mode

.releaserc.json
Add release config file, to create automated releases.
=> feat: Add .releaserc.json

LICENSE
=> fix: Update license copyright message

.releaserc.json
=> fix: Remove semantic-release/github plugin

.releaserc.json
This reverts commit f5544523fc4a9c985fd4222e4c941ad7cbac089a.
=> feat: Add semantic-release/github plugin

docs/prerequisites.md, playbooks/1_create_lpar.yaml
Automatically install ibm.ibm_zhmc collection's python package dependencies, and update docs to match.
Signed-off-by: Jacob Emery <jacob.emery@ibm.com>
=> feat: Automate install of zhmc dependencies

roles/wait_for_bootstrap/tasks/main.yaml
Adjust bootstrap wait time. The duration depends highly on network speed and system performance.
=> fix: Adjust bootstrap wait time

docs/run-the-playbooks-for-hypershift.md
Adding vault in documentation for hypershift
=> Fix: Change in documentation Adding vault

roles/approve_certs/tasks/main.yaml
Increase csr wait time, to resolve low network performance issues.
=> fix: Increase csr wait time

roles/check_nodes/tasks/main.yaml
Show node status with architecture type.
=> chore: Improve node check

docs/run-the-playbooks.md, docs/set-variables-group-vars.md, inventories/default/group_vars/all.yaml.template, playbooks/create_compute_node.yaml, playbooks/delete_compute_node.yaml, roles/create_compute_node/tasks/main.yaml, roles/create_compute_node/vars/main.yaml, roles/delete_compute_node/tasks/main.yaml, roles/delete_compute_node/vars/main.yaml, roles/dns_update/tasks/add.yaml, roles/dns_update/tasks/delete.yaml, roles/dns_update/tasks/main.yaml, roles/dns_update/vars/main.yaml, roles/print_node_status/tasks/main.yaml, roles/update_ignition_files/defaults/main.yml, roles/update_ignition_files/tasks/main.yml, roles/wait_for_node/tasks/main.yaml, roles/wait_for_node/vars/main.yaml
Add support to create additional compute nodes (day-2) with different architecture and to delete existing compute nodes.
=> feat: Add and delete compute nodes (day-2)

roles/common/tasks/print_ocp_node_status.yaml, roles/create_bootstrap/tasks/main.yaml
Add additional output to improve debug.
=> chore: Minor debug improvements

docs/run-the-playbooks.md, docs/set-variables-host-vars.md, inventories/default/host_vars/KVMhostname1-here.yaml.template, inventories/default/host_vars/KVMhostname2-here.yaml.template, inventories/default/host_vars/KVMhostname3-here.yaml.template, playbooks/0_setup.yaml, playbooks/1_create_lpar.yaml, playbooks/2_create_kvm_host.yaml, playbooks/3_setup_kvm_host.yaml, playbooks/4_create_bastion.yaml, playbooks/5_setup_bastion.yaml, playbooks/6_create_nodes.yaml, playbooks/reinstall_cluster.yaml, roles/configure_storage/tasks/main.yaml, roles/configure_storage/templates/vdisk.xml.j2, roles/create_bastion/tasks/main.yaml, roles/create_bootstrap/tasks/main.yaml, roles/create_compute_nodes/tasks/main.yaml, roles/create_control_nodes/tasks/main.yaml, roles/macvtap/tasks/main.yaml, roles/prep_kvm_guests/tasks/main.yaml, roles/update_cfgs/tasks/main.yaml, roles/update_cfgs/templates/kvm_host.prm.j2
Reverts IBM/Ansible-OpenShift-Provisioning#107
=> Revert "Unprivileged kvm admin dev"

docs/run-the-playbooks-for-hypershift.md, roles/create_agentserviceconfig_hypershift/tasks/main.yaml, roles/create_hcp_InfraEnv_hypershift/tasks/main.yaml, roles/install_prerequisites_host_hypershift/tasks/main.yaml
- Updated change  to use ansible module for ssh key generation
- Giving comment for key as Ansible-OpenShift-Provisioning SSH key
=> Updated change  to use ansible module for ssh key generation

roles/create_bastion_hypershift/tasks/main.yaml, roles/create_hcp_InfraEnv_hypershift/tasks/main.yaml, roles/create_inventory_setup_hypershift/tasks/main.yaml, roles/create_inventory_setup_hypershift/templates/ssh-key.exp.j2
Changed ssh key path - Hypershift 
- Changed the path for ssh key on local host 
- Removed space while creating HCP which is causing issue while using different basedomian
=> Fix : Changed ssh key path - Hypershift 

playbooks/create_compute_node.yaml
This patch detects the required RHCOS images to install a compute node.
=> feat: Detect automatically required RHCOS images for compute nodes

roles/add_hc_workers_to_haproxy_hypershift/tasks/main.yaml, roles/download_rootfs_hypershift/tasks/main.yaml
Changed port for httpd configuration
- Earlier we used port 443 and 8080 for httpd , but we have conflict with port 443 while configuring HAProxy in later stages.
- So changed the port from 443 to 8443
=> Enhancement: Changed port for httpd configuration

mkdocs.yaml
Update mkdocs.yaml file to include run-the-playbooks-for-hypershift.md, and to remove CHANGELOG file as it has been replaced with semantic-release.
=> docs: add hypershift, remove CHANGELOG from mkdocs.yaml

playbooks/create_compute_node.yaml
=> fix: Improve error handling

roles/delete_resources_bastion_hypershift/tasks/main.yaml, roles/install_mce_operator/templates/ClusterImageSet.yaml.j2
- Added ClusterImageSet creation for nightly build image
=> Fix: Added ClusterImageSet creation for nightly build image

roles/dns/tasks/initial-resolv.yaml
=> fix: Typo in initial-resolv.yaml

playbooks/create_compute_node.yaml, playbooks/delete_compute_node.yaml, playbooks/reinstall_cluster.yaml, roles/haproxy/templates/haproxy.cfg.j2, roles/haproxy_update/tasks/add.yaml, roles/haproxy_update/tasks/delete.yaml, roles/haproxy_update/tasks/main.yaml, roles/haproxy_update/vars/main.yaml
This patch updates the HAProxy.cfg file during compute node install and removal.
=> fix: Update HAProxy.cfg during day-2 compute node install

docs/set-variables-group-vars.md, inventories/default/group_vars/all.yaml.template, roles/create_bastion/tasks/main.yaml, roles/create_bootstrap/tasks/main.yaml, roles/create_compute_node/tasks/main.yaml, roles/create_compute_nodes/tasks/main.yaml, roles/create_control_nodes/tasks/main.yaml
With this patch you can boot bastion, bootstrap node, control node and compute node via DHCP service.
Infra nodes are not supported yet.
=> feat: Add DHCP support

roles/delete_nodes/tasks/main.yaml
Remove pipefail option and simplify loop definition.
=> fix: Remove pipefail option

roles/dns/tasks/main.yaml, roles/get_ocp/tasks/main.yaml, roles/get_ocp/templates/install-config.yaml.j2, roles/haproxy/tasks/main.yaml
Execute function when required compute node variables are defined.
=> fix: Check if compute nodes are defined

playbooks/6_create_nodes.yaml
Deleteing all the entries related bootstrap  in haproxy config after its    ###deletion. # # #
=> Deleting entries related to Bootstrap in Haproxy post its deletion

roles/check_dns/tasks/main.yaml, roles/dns/tasks/main.yaml
This patch fixes #252 'setup bastion fails for 3 node cluster'
=> fix: DNS issues

roles/create_compute_nodes/tasks/main.yaml, roles/dns/tasks/main.yaml, roles/haproxy/tasks/main.yaml
This patch checks for compute node hostname variable and compute node hostname array value.
=> chore: Improve compute node hostname check

README.md, inventories/default/group_vars/all.yaml.template, playbooks/5_setup_bastion.yaml
Disable openvpn and set to deprecated and will be removed in upcoming releases.
=> fix: Partial fix for #160 (RHEL support).

docs/set-variables-host-vars.md, inventories/default/host_vars/KVMhostname1-here.yaml.template, inventories/default/host_vars/KVMhostname2-here.yaml.template, inventories/default/host_vars/KVMhostname3-here.yaml.template, roles/boot_LPAR/tasks/main.yaml, roles/boot_LPAR/templates/boot_lpar.py
Enables to use the FCP live disk to boot the nodes.
=> Livedisk with FCP changes

roles/boot_abi_agents/tasks/main.yml, roles/prepare_configs/templates/agent-config.yaml.j2
Encountering 'dict object' has no attribute 'bridge_name' and 'mac_address' in Ansible Playbook For ABI
=> Fix for the Issue-283 

roles/boot_abi_agents/tasks/main.yml
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/291
=> Exception occurred while running ABI with different metadata name

README.md
Update README based on release v.2.1.0
=> Update README based on release v2.1.0

roles/boot_LPAR/tasks/main.yaml
Boot the LPAR with DASD disks.
=> LPAR boot with dasd disks

roles/create_agentserviceconfig_hcp/tasks/main.yaml, roles/create_hcp_InfraEnv/tasks/main.yaml, roles/create_inventory_setup_hcp/templates/ssh-key.exp.j2
- Fixed one variable typo issue
- Changed the way of getting hcp binary from pod
- Updated Agentserviceconfig creation role
=> HCP variables mismatch issue has been fixed along with enhancements

playbooks/master_playbook_for_abi.yaml, playbooks/monitor_create_abi_cluster.yaml, roles/abi_install_complete/tasks/main.yaml, roles/boot_abi_agents/tasks/main.yml
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/302
=> ABI: Added Monitoring For ABI Cluster Installation

docs/set-variables-group-vars.md, inventories/default/group_vars/all.yaml.template
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/311
=> Added and define default value for Missing Parameter in all.yaml 

docs/set-variables-group-vars.md, inventories/default/group_vars/hcp.yaml.template, roles/create_bastion_hcp/tasks/main.yaml, roles/create_hcp_InfraEnv/tasks/main.yaml
- Updated hcp binary extraction procedure
- Removes os_variant  variable in bastion creation, as it can fetch from installation media 
- Updated documentation
=> Fix: Updated hcp binary extraction procedure and enahancements

roles/create_bastion_hcp/tasks/main.yaml, roles/scale_nodepool_and_wait_for_compute_hcp/tasks/main.yaml
Fixed namespace issue in wait for agents - hcp
=> fix: resolved namespace issue in wait for agents - hcp

docs/set-variables-group-vars.md, inventories/default/group_vars/hcp.yaml.template, roles/boot_LPAR_hcp/tasks/main.yaml, roles/boot_zvm_nodes/tasks/main.yaml, roles/delete_resources_bastion_hcp/tasks/main.yaml, roles/delete_resources_kvm_host_hcp/tasks/main.yaml, roles/install_mce_operator/templates/Subscription.yaml.j2
- Updated deletion procedure for HCP 
- Updated MCE creation role to take catalogsource name from user input
=> Enhancement: Updated deletion procedure for HCP 

roles/abi_install_complete/tasks/main.yaml
Included task to ssh into control and compute nodes post successful installation of cluster.
=> Included task to ssh into control and compute nodes post successful installation of cluster

roles/create_bastion/tasks/main.yaml
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/381
=> Fix has been added for Bastion is not coming up fips enabled

playbooks/destroy_abi_cluster.yaml, roles/delete_nodes/tasks/main.yaml
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/383
=> Destroy ABI has been fixed.

roles/abi_install_complete/tasks/main.yaml, roles/create_bastion/tasks/main.yaml, roles/install_packages/tasks/main.yaml
Added print statement after install-complete
Increased timeout while creating bastion
Modified reading os version in install_packages role
=> Jenkins Fix has been added 

roles/create_hcp_InfraEnv/templates/InfraEnv.yaml.j2, roles/download_rootfs_hcp/tasks/main.yaml, roles/setup_for_agents_hcp/tasks/main.yaml
Updated InfraEnv template 
Updated timeouts for image downloads
=> fix: Updated InfraEnv template and updated timeouts for image downloads 
