- roles/check_dns/tasks/main.yaml
Hi @jacobemery  @ftmiranda, 
I just saw #35 and noticed that the dns_check role doesn't fail based on the output. We need to examine the output because a host that does not exists is not considered an error in the `nslookup` world.
This PR adds the functionality to fail the step if the nslookup output contains
`server can't find`
In the code I only check for `server can` because I didn't find a way to escape the "`"..
> Fail dns_check step depending on nslookup output

- roles/create_bootstrap/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/create_control_nodes/tasks/main.yaml
During installation an own storage pool is being created named: {{ env.cluster.networking.metadata_name }}-vdisk
During installation of following nodes: bootstrap, control, compute and infra the default pool is being used rather than the newly created storage pool. 
This may lead to errors during execution of the playbook scripts because the file path of default storage pool may differ from storage path for newly created pool. 
This fix uses the newly created ({{ env.cluster.networking.metadata_name }}-vdisk) pool instead of the default pool.
> Fix for the default storage pool usage. Use newly created storage pool.

- docs/set-variables-group-vars.md
- playbooks/6_create_nodes.yaml
- playbooks/7_ocp_verification.yaml
- roles/get_ocp/tasks/main.yaml
Sometimes it is necessary (and very convenient) to work with the root user instead of using a specific user with sudo access.
Especially when used in a closed test environment in which various automation tests are being executed. 
This fix enables root user support for edge use cases.
> Enable root user as installing user

- roles/create_bastion/tasks/main.yaml
Changed 'virt-isntall' to 'virt-install' on line 61  (Find FTP home for use in next step)
Signed-off-by: Barry Silliman silliman@us.ibm.com
> Fix typo in tag

- .ansible-lint
Add ansible-lint config file. Ansible Lint is a command-line tool for linting playbooks, roles and collections aimed toward any Ansible users. Its main goal is to promote proven practices, patterns and behaviors while avoiding common pitfalls that can easily lead to bugs or make code harder to maintain.
Signed-off-by: Klaus Smolin <SMOLIN@de.ibm.com>
> feat: Add .ansible-lint

- .editorconfig
Add .editorconfig to have consistent coding styles across editors and IDEs.
Signed-off-by: Klaus Smolin <SMOLIN@de.ibm.com>
> feat: Add .editorconfig

- docs/set-variables-group-vars.md
- inventories/default/group_vars/.gitignore
- inventories/default/group_vars/all.yaml.template
The inventory file 'all.yaml' is part of the current git structure. This file is always modifed to execute Ansible-OpenShift-Provisioning and therefore it will be tracked in your git branch as modifed. But, it will not be commited, because it contains credentials !
This patch renames the original file to a template filename. The user needs to create a local 'all.yaml' copy.
Signed-off-by: Klaus Smolin <SMOLIN@de.ibm.com>
> feat: Untrack all.yaml file in git

- roles/ssh_copy_id/tasks/main.yaml
- roles/ssh_copy_id/templates/ssh-copy-id.exp.j2
- roles/ssh_key_gen/tasks/main.yaml
- roles/ssh_ocp_key_gen/tasks/main.yaml
fix: Set timeout for ssh-copy-id, do not wait forever
fix: Force ssh-copy-id, to avoid issues if the key already exists
fix: Duplicate creation of 'path_to_key_pair' variable in 'all.yaml' file
> fix(ssh): Some minor fixes

- playbooks/6_create_nodes.yaml
- playbooks/reinstall_nodes.yaml
- roles/delete_nodes/tasks/main.yaml
In case you want to re-install the cluster, because of an install problem or of a new OCP version, then you can just execute playbooks:
* 6_create_nodes.yaml
* 7_ocp_verification.yaml
In order to have a clean setup on each run, we delete all existing control, compute and infra nodes. Bastion node will not be deleted.
> feat: Add delete_nodes role

- playbooks/5_setup_bastion.yaml
- playbooks/6_create_nodes.yaml
- roles/create_bootstrap/tasks/main.yaml
Delete correct bootstrap qcow2 image.
The bootstrop VM is deleted after creation of control nodes. But, in case of an issue, the VM is not deleted. New config bootstrap changes are ignored, because the existing old bootstrap VM is used on the next executions until the VM is manually deleted.
We are now deleting and creating the bootstrap VM on each test run, to solve the above issue.
> fix(bootstrap): Deletion of existing VM image

- roles/wait_for_bootstrap/tasks/main.yaml
The openshift-installer requires up to 60 min to complete. You need to check manually if the install process started sucessfully or you simply wait 60 min for the results.
This patch monitors the 'node-bootstrapper' request. Usually such request is raised within 6 min. If not, then this is considered as an error and the ansible playbook script exits.
The openshift-installer process is not aborted! It is still running.
> fix: Improve output of openshift-installer progress and check

- roles/wait_for_cluster_operators/defaults/main.yml
- roles/wait_for_cluster_operators/tasks/check_co.yaml
- roles/wait_for_cluster_operators/tasks/main.yaml
Replace seven static tasks to check cluster operators, with a task loop.
> fix: Improve waiting for cluster operators check

- roles/create_bastion/tasks/main.yaml
- roles/create_bastion/templates/bastion-ks.cfg.j2
The required parameter "--extra-args" was removed in the virt-install command.
This is causing the VM creation to fail. 
Therefore removing the patch until a new patch is available.
> Revert bastion nameserver patch

- roles/dns/files/90-dns-none.conf
- roles/dns/tasks/main.yaml
- roles/dns/templates/resolv.conf.j2
NetworkManager will update /etc/resolv.conf file on next restart or reboot. We need to disable it.
> fix: Disable /etc/resolv.conf updates by NetworkManager

- roles/check_nodes/tasks/main.yaml
Verify the status of all defined control and compute nodes. The old code just checked if reported nodes where 'Ready'. The reported node list was not verified.
> fix: Improve node check

- playbooks/reinstall_cluster.yaml
Add prep_kvm_guests role call to reinstall_cluster playbook so that new versions of the kernel and initramfs are pulled down if the OCP version changes in inventory.
Signed-off-by: Jacob Emery <jacob.emery@ibm.com>
> Additional artifact refresh

- inventories/default/group_vars/all.yaml.template
The yum group @virt does not exists anymore in RHEL9. We install now the files which where defined in that group.
This solution will work for RHEL8 and RHEL9 KVM host installs.
> fix: Group virt does not exist in RHEL9

- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- roles/create_bootstrap/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/create_control_nodes/tasks/main.yaml
- roles/get_ocp/tasks/main.yaml
- roles/prep_kvm_guests/tasks/main.yaml
Previous method for selecting the OpenShift version in all.yaml was unnecessarily cumbersome, requiring copying 5 different mirror links to variables.
This make it so you just set one variable env.openshift.version to the desired version (i.e. 4.12) and the automation does the rest.
Signed-off-by: Jacob Emery <jacob.emery@ibm.com>
> feat: Improve OCP versioning

- docs/prerequisites.md
- docs/run-the-playbooks.md
- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- playbooks/0_setup.yaml
- playbooks/2_create_kvm_host.yaml
- roles/create_bastion/tasks/main.yaml
- roles/create_bastion/templates/bastion-ks.cfg.j2
- roles/create_kvm_host/tasks/main.yaml
- roles/set_inventory/tasks/main.yaml
- roles/set_inventory/templates/hosts.j2
- roles/update_cfgs/tasks/main.yaml
- roles/update_cfgs/templates/kvm_host.cfg.j2
- roles/update_cfgs/templates/kvm_host.prm.j2
Related to Issue #96 
The name 'FTP server' is confusing since the KVM host is now capable of hosting and serving necessary files via http only. Update the docs and variables to represent this change. 
Also, enable using either ftp or http to serve config files for the bastion. FTP is still the only option for booting the KVM hosts, as that is the only option for the HMC to network boot from. And HTTP will still be installed and used on the bastion as it is required. But with these changes, someone using a pre-existing KVM host and NAT-based networking can use only HTTP if they'd like. And someone using an FTP server for booting of the KVM host(s) can use that same FTP server to boot the bastion.
> fix: Change ftp server to file server

- inventories/.gitignore
Add this gitignore file to allow for the creation, and use of, alternate inventories, while avoiding inadvertently pushing them to a public repo.
The desired inventory could then easily be selected (and switched between) by altering the 'inventory=inventories/<desired-inventory>' line in ansible.cfg
> fix: Add gitignore to inventories

- playbooks/pre-existing_site.yaml
Sudo access is required to setup a KVM host. In a pre-existing env, we assume that the KVM host is already installed.
> fix: Remove '3_setup_kvm_host' from 'pre-existing_site' playbook

- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- roles/create_bastion/tasks/main.yaml
- roles/create_bootstrap/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/create_control_nodes/tasks/main.yaml
- roles/get_ocp/tasks/main.yaml
- roles/prep_kvm_guests/tasks/main.yaml
This patch provides the user the ability to specify the OCP and the RHCOS version separately.
> fix: Separate RHCOS and OCP versions

- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- roles/create_bastion/templates/bastion-ks.cfg.j2
signed-off-by: Amadeuds Podvratnik [pod@de.ibm.com](mailto:pod@de.ibm.com)
This fix adds support for the keyboard layout to the kickstart file to the create bastion playbook.
> Fix: Add keyboard layout support to bastion kickstart template

- playbooks/6_create_nodes.yaml
For multi-arch we need to define two KVM hosts. The second host is motlikly based on a different architecture. We need to make sure that the bootstrap host is based on the same architecture as the control node host.
> chore: Install bootstrap on first KVM host

- roles/configure_storage/templates/vdisk.xml.j2
The storage pool uuid is defined during creation of a new storage pool. It should not be part of the template file.
> fix: Remove uuid from storage template file

- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- roles/get_ocp/tasks/main.yaml
With this patch you are able to test OCP nightly builds.
> chore: Use new OCP version and download variables

- roles/wait_for_cluster_operators/tasks/check_co.yaml
Some cluster operators are in 'AVAILABLE' state, but are still in 'PROGRESSING' state. We must make sure that all cluster operators have completed their setup.
> fix: Check for 'PROGRESSING' state, instead 'AVAILABLE' state

- playbooks/create_compute_node.yaml
- playbooks/delete_compute_node.yaml
Update Bastion DNS entries only when enabled.
> fix: Update Bastion DNS entries only when enabled

- docs/run-the-playbooks-for-hypershift.md
- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- playbooks/create_hosted_cluster.yaml
- roles/boot_agents_hypershift/tasks/main.yaml
- roles/create_hcp_InfraEnv_hypershift/tasks/main.yaml
- roles/create_hcp_InfraEnv_hypershift/templates/InfraEnv.yaml.j2
- roles/create_hcp_InfraEnv_hypershift/templates/nmStateConfig.yaml.j2
- roles/delete_resources_bastion_hypershift/tasks/main.yaml
- roles/install_mce_operator/tasks/main.yaml
- roles/install_mce_operator/templates/ClusterImageSet.yaml.j2
- roles/install_mce_operator/templates/MultiClusterEngine.yaml.j2
- roles/install_mce_operator/templates/OperatorGroup.yaml.j2
- roles/install_mce_operator/templates/Provisioning.yaml.j2
- roles/install_mce_operator/templates/Subscription.yaml.j2
Added  changes required for supporting Static IP configuration
- Adds labels to InfraEnv 
- Deploy NMStateConfig resources for Static IP configuration
Updated documentation for the same
> feat: Static IP support for agents using NMState and MCE operator install  - Hypershift

- .github/workflows/main.yaml
This adds a new workflow to GitHub Actions.
The action deploys an updated version of the documentation to GitHub Pages.
It is triggered when changes are pushed to 'mkdocs.yaml' or anything under the 'docs' folder on the 'main' branch.
This is necessary to make the docs up-to-date with our code, without manual intervention.
Tested on my fork, although it required some tweaking there to adjust it for testing purposes, so it might take some troubleshooting here in the upstream.
> docs: automate docs deployment on update

- .github/workflows/main.yaml
Hotfix to #196 that automates GitHub Pages deployments. Looks like the workflow failed in error because it didn't have the most recent version of the gh-pages branch. This PR will hopefully fix that issue.
> fix: pull updated gh-pages

- playbooks/5_setup_bastion.yaml
There are several open issues related to DNS. DNS setup needs to be verified. We ignore some DNS check results for now, because of issue 166, 182.
> fix: Temporary ignore some DNS checks

- roles/create_bootstrap/tasks/main.yaml
- roles/create_compute_node/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/create_control_nodes/tasks/main.yaml
The creation of VM's requires more time on low performance systems.
> fix: Increase timeout from 300 to 360 sec

- roles/create_bastion/templates/bastion-ks.cfg.j2
OCP install will fail, if you use ipv4 setup only. Because of misisng quotes arround '--noipv6' keyword.
> fix: Missing quotes in 'Add ipv6 support' patch

- roles/boot_agents_hypershift/tasks/main.yaml
- roles/create_bastion/tasks/main.yaml
- roles/create_bootstrap/tasks/main.yaml
- roles/create_compute_node/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/create_control_nodes/tasks/main.yaml
This patch contains only code style changes !
In preperation to add dhcp support or other network changes, it is required to split the very long --extra-args into several single --extra-args which are used by virt-install.
> chore: Reformat long virt-install arguments

- playbooks/create_compute_node.yaml
- roles/delete_compute_node/tasks/main.yaml
Execute function when required variable is defined.
> fix: Execute function when required variable is defined

- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- roles/create_bastion/tasks/main.yaml
- roles/create_bastion/templates/bastion-ks.cfg.j2
- roles/create_bootstrap/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/create_control_nodes/tasks/main.yaml
- roles/delete_compute_node/tasks/main.yaml
- roles/delete_nodes/tasks/main.yaml
This patch contains several changes which are required to install
OCP on a ARM server.
The new variable 'vcpu_model_option' can be used to configure the
CPU model and CPU features exposed to the guest. The default CPU
model 'host' is currently not supported on ARM servers and must be
defined to the desired value.
> feat: Add support for ARM KVM server

- docs/set-variables-group-vars.md
This fix updates the documentation for ip_forward variable. It describes what kind of ip_forward is meant.
Issue #162
> Fix for - NAT vs IPForward documentation clarity #162

- docs/run-the-playbooks.md
- roles/check_nodes/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/haproxy/tasks/main.yaml
With this patch you can create a three node OCP cluster, without dedicated compute nodes. You just need to uncomment the compute node hostname definition in the config file (all.yaml).
> feat: Add support to create a three node OCP cluster

- roles/create_bastion/tasks/main.yaml
- roles/create_bootstrap/tasks/main.yaml
- roles/create_compute_node/tasks/main.yaml
- roles/create_compute_nodes/tasks/main.yaml
- roles/create_control_nodes/tasks/main.yaml
Disable disk device cache, because this is recommended in the OCP docs (chapter: "Recommended host practices for IBM Z & IBM LinuxONE environments").
> fix: Disable disk device cache

- playbooks/5_setup_bastion.yaml
- fix the report error when check 'expect' package on jumphost
- the error look "...failed_when_result": "The conditional check ''expect' not in ansible_facts.packages' failed. The error was: error while evaluating conditional ('expect' not in ansible_facts.packages): 'dict object' has no attribute 'packages'. 'dict object' has no attribute 'packages'"}
Fixes https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/296
Signed-off-by: Da Li Liu <liudali@cn.ibm.com>
> issue296: use another way to check 'expect' package on jumphost

- roles/wait_for_install_complete/tasks/main.yaml
This patch solves a hung condition during update of /etc/hosts when
you use a container as control host.
> fix: Hung condition during update of /etc/hosts

- roles/create_bastion/templates/rhel9-bastion-ks.cfg.j2
Fix has been added for issue 337.
``install_config``` was causing issue as it has been renamed as ```install_config_vars``` but it was not rectified in ```create_bastion`` roles.
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/337
> Fix: Create bastion with rhel version 9 is failing in latest code

- playbooks/5_setup_bastion.yaml
Skipping the tasks related to hipersocket when installation_type is not lpar
> FIX: ISSUE NO 343

- roles/boot_abi_agents/tasks/main.yml
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/347
> Creation of ABI cluster is getting failed on KVM (os version rhel9) #347

- roles/install_packages/defaults/main.yaml
Added fix for issue KVM Setup playbook is failling while operating on httpd server
RCA: It was getting failed due to httpd server was not installed and playbook trying to perform few operation on httpd
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/336
> Added fix for issue 336

- roles/boot_agents_hcp/tasks/main.yaml
- roles/boot_zvm_nodes_hcp/tasks/main.yaml
- roles/create_hcp_InfraEnv/tasks/main.yaml
- roles/create_hcp_InfraEnv/templates/InfraEnv.yaml.j2
- roles/create_hcp_InfraEnv/templates/nmStateConfig.yaml.j2
- roles/delete_resources_bastion_hcp/tasks/main.yaml
- roles/delete_resources_kvm_host_hcp/tasks/main.yaml
- roles/download_rootfs_hcp/tasks/main.yaml
- roles/scale_nodepool_and_wait_for_compute_hcp/tasks/main.yaml
- roles/setup_for_agents_hcp/tasks/main.yaml
**HCP Workflow change :** 
- Segregating InfraEnv and Agents into a separate namespace while creating and destroying HCP
- This caters to the best practice installation of HCP and also makes sure the Hosted Control Plane and Data Plane are completely segregated which helps to manage Hosted Cluster easily
**Tested Builds :** [HCP Creation](https://sys-soltest-team-jenkins.swg-devops.com/job/OCP-BOE/job/BOE-HCP/job/agent-hcp-create/354/console) & [HCP Deletion](https://sys-soltest-team-jenkins.swg-devops.com/job/OCP-BOE/job/BOE-HCP/job/agent-hcp-destroy/)
> fix: HCP - Segregating InfraEnv and Agents into a separate namespace

- roles/disconnected_mirror_images/tasks/main.yaml
- roles/disconnected_mirror_images/templates/resolv.conf.j2
- roles/dns/templates/dns.db.j2
- roles/offline_artifacts/tasks/main.yaml
This is pull request is having fix for below two issue  (ABI Disconnected)
[OpenShift Client in not getting download from file_server ](https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/366)
[ABI: On fresh z/VM bastion ABI playbook is not installing tessia base lib](https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/365)
> OpenShift Client issue has been resolved along with DNS issue

- playbooks/5_setup_bastion.yaml
- roles/setup_params/tasks/main.yaml
z/VM:
Fix the python issue
Fix the tessia base lib download issue
Fix the KVM code usage; regarding the /var/lib/libvirt/images/pxe directory creation usage
https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/369
> Required packages was not getting installed on z/vm bastion

- roles/install_packages/defaults/main.yaml
- roles/install_packages/tasks/main.yaml
RCA: Playbook was getting failed due to libvirt-devel packages that is not available for rhel9. 
Fix: Removed libvirt-devel from packages list and installing it only when rhel version in below 9.
This PR contain fix for [Playbook 3_setup_kvm_host is getting failed on LPAR os version rhel9 or above](https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/360)  .
> Playbook 3_setup_kvm_host is getting failed on LPAR os version rhel9 or above

- playbooks/create_abi_cluster.yaml
- roles/abi_install_complete/tasks/main.yaml
Shifted the SSH login setup for control and compute nodes from the bastion to the ABI cluster creation playbook
> Shifted the SSH login setup for control and compute nodes from the bastion to the ABI cluster creation playbook

- playbooks/destroy_abi_cluster.yaml
This PR contains fix for destroy ABI cluster playbook while enabling jankins pipeline.
> Fix AOP Code for Destroy ABI Cluster On KVM 

- roles/abi_install_complete/defaults/main.yaml
- roles/abi_install_complete/tasks/main.yaml
- roles/abi_install_complete/vars/main.yaml
1. Agent was not waiting more then the default time so Increased timeout by 25 min 
2. In case of fips enabled it was getting failed. as fips binary was not getting use to monitor the status
3. Added Extra login details at the end of cluster installation.
> Agent was not waiting more than the default time

- roles/boot_abi_agents/tasks/main.yml
Sporadic: All nodes are not getting boot while creating ABI cluster using AOP https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/399
> Added delay in async job as disk-pool was not available for all async job at same time.

- roles/abi_install_complete/tasks/main.yaml
- roles/create_agent/tasks/main.yml
**Issue:** ABI cluster creation is getting failed in 4.19 installer version https://github.com/IBM/Ansible-OpenShift-Provisioning/issues/401
**RCA:** From 4.19 ocp installer have started generating boot-artifacts with different name like  agent.s390x-kernel.img as  agent.s390x-vmlinuz. While booting agents we are providing agent.s390x-kernel.img as expected but now agent.s390x-kernel.img is not present in boot-artifacts
**Fix:**  Renamed agent.s390x-vmlinuz as agent.s390x-kernel.img because  agent.s390x-vmlinuz has same content as agent.s390x-kernel.img
> Fix: Boot-artifacts has been renamed as required to boot the agents.

- docs/set-variables-group-vars.md
- inventories/default/group_vars/all.yaml.template
- roles/download_ocp_installer/tasks/main.yaml
This PR adds support for downloading OpenShift installer and client binaries for both single (s390x) and multi-architecture (multi) configurations.
Changes:
Dynamically constructs the download URL based on the value of abi.architecture.
For multi, appends the architecture-specific subdirectory (s390x/) to the URL.
Ensures the correct binaries are fetched and extracted regardless of the architecture setup.
Purpose:
To streamline support for multi-arch environments while maintaining compatibility with existing single-architecture deployments.
> Multiarch support for abi

- roles/boot_LPAR/templates/boot_lpar.py
This pull request introduces changes to support the use of DASD (Direct Access Storage Device) as the livedisk for booting an LPAR (Logical Partition).
> Changes to support DASD livedisk for LPAR

- .github/workflows/ansible_linter.yaml
- .github/workflows/pr_metadata_checks.yaml
Added workflows to integrate github actions for PR validations
This change will enable 3 jobs :
1. Validate PR title
2. Check for the description 
3. Ansible lint check for the files changed as part of the PR raised.
As a first step,  adding these checks. we can make 1 & 2 as mandatory checks and 3 as an optional check.
> feat: Added workflows to integrate github actions for PR validations

- roles/create_agentserviceconfig_hcp/templates/mirror-config.yml.j2
- roles/create_hcp_InfraEnv/templates/icsp.yaml.j2
Updated mirror information for HCP templates
- Added quay.io:443 as mirror for registry.redhat.io/multicluster-engine , as we are getting new builds in quay.io:443
> fix: Updated mirror information for HCP templates
